--- #第一个服务提供者的实列
server:
  port: 8763
spring:
  profiles: instance1
  application:
    name: eureka-client   #服务名 服务提供者需要提供，远程调用时使用

eureka:
  client:
    serviceUrl:
       #defaultZone: http://peer1:8761/eureka/  #Eureka Server的注册地址
     defaultZone: http://localhost:8761/eureka/  #Eureka Server的注册地址

--- #第二个服务提供者的实列
server:
  port: 8765
spring:
  profiles: instance2
  application:
    name: eureka-client   #服务名  服务提供者需要提供，远程调用时使用

eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer1:8761/eureka/  #Eureka Server的注册地址
     defaultZone: http://localhost:8761/eureka/  #Eureka Server的注册地址

