--- #该文件为单节点启动测试
spring:
  profiles: single-node
server:
  port: 8761

eureka:
  instance:
    hostname: single-node
  client:
    register-with-eureka: false  #不会注册到自身
    fetch-registry: false #不需要向其他节点获取注册表
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---   #多profiles分割符，集群文件1
spring:
  profiles: peer1
server:
  port: 8761  #自己的服务端口
eureka:
  instance:
    hostname: peer1 #server ip
  client:
    #register-with-eureka: false  #是否将自己注册到Eureka服务器
    #fetch-registry: false  #
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/ #eureka 完整配置地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #eureka 完整配置地址

---   #多profiles分割符,集群文件2
spring:
  profiles: peer2
server:
  port: 8762  #自己的服务端口
eureka:
  instance:
    hostname: peer2 #ip
  client:
    #-with-eureka: false  #是否将自己注册到Eureka服务器
    #fetch-registry: false  #
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/ #eureka 完整配置地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #eureka 完整配置地址
