spring:
  application:
    name: service-turbine
server:
  port: 8767

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  instanceUrlSuffix: /hystrix.stream  #没有的话会出现异常
  aggregator:
    cluster-config: default
  appConfig: eureka-ribbon-client,eureka-feign-client
  clusterNameExpression: new String("default")
